### ISSUE TITLE
cronLaunch.php causes DI compile to fail

### ISSUE THREAD

**Issue by adamj88** [salesfire/magento2#1]
The `cronLaunch.php` file is causing DI compile (`bin/magento setup:di:compile`) to fail on the latest release, v1.2.1 - what is the purpose of this file?

Seems to be requiring `app/bootstrap.php` which shouldn't be there.

```Compilation was started.
%message% 0/7 [>---------------------------]   0% < 1 sec 104.0 MiB
%message% 0/7 [>---------------------------]   0% < 1 sec 104.0 MiB
Proxies code generation... 0/7 [>-----------------------]   0% < 1 sec 104.0 MiB
Proxies code generation... 1/7 [===>--------------------]  14% 4 secs 110.0 MiB
Repositories code generation... 1/7 [==>-----------------]  14% 4 secs 110.0 MiB
Warning: Uncaught Exception: Warning: require(../app/bootstrap.php): failed to open stream: No such file or directory in vendor/salesfire/magento2/cronLaunch.php on line 2 in vendor/magento/framework/App/ErrorHandler.php:61
Stack trace:
#0 vendor/salesfire/magento2/cronLaunch.php(2): Magento\Framework\App\ErrorHandler->handler(2, 'require(../app/...', '...', 2, Array)
#1 vendor/salesfire/magento2/cronLaunch.php(2): require()
#2 setup/src/Magento/Setup/Module/Di/Code/Reader/ClassesScanner.php(126): require_once('...')
#3 setup/src/Magento/Setup/Module/Di/Code/Reader/ClassesScanner.php(111): Magento\Setup\Module\Di\Code\Reader\ClassesScanner->includeClasses(Array, '...')
#4 setup/ in vendor/magento/framework/App/ErrorHandler.php on line 61

Fatal error: Magento\Setup\Module\Di\Code\Reader\ClassesScanner::main(): Failed opening required '../app/bootstrap.php' (include_path='generated/code:generated/code:vendor/magento/zendframework1/library:.:/usr/local/lib/php') in vendor/salesfire/magento2/cronLaunch.php on line 2```

**Comment by StephenHonor** [comment]
This has been resolved - it was only added to be able to test the feeds but its been removed.

Please let us know if you have any further issues with the new version.
